line-length = 100
target-version = "py312"
extend-exclude = ["data"]
src = ["src"]

[lint]
select = ["E","F","I","W","UP","B","PL","RUF"]
ignore = ["E501","PLR0912","PLR0915"]

[format]
quote-style = "double"
