name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # needed to push coverage-badge.svg

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Sync dependencies (main + dev)
        run: |
          uv sync --dev

      - name: Lint & type-check
        run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run mypy src tests

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=src --cov-report=xml --cov-report=term

      - name: Generate coverage badge
        run: |
          uv run python -m pip install "genbadge[coverage]"
          uv run python -m genbadge.coverage -i coverage.xml -o coverage-badge.svg

      - name: Commit coverage badge (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if git diff --quiet coverage-badge.svg 2>/dev/null; then
            echo "No coverage badge changes"
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add coverage-badge.svg
            git commit -m "chore: update coverage badge [skip ci]" || echo "No changes to commit"
            git push
          fi
